---
default_set: 'centos-64-x64'
sets:
  'centos-59-x64':
    nodes:
      "centos5.serf.vm":
        prefab: 'centos-59-x64'
  'centos-64-x64':
    nodes:
      "centos6.serf.vm":
        prefab: 'centos-64-x64'
  'fedora-18-x64':
    nodes:
      "fedora18.serf.vm":
        prefab: 'fedora-18-x64'
  'debian-607-x64':
    nodes:
      "debian6.serf.vm":
        prefab: 'debian-607-x64'
  'debian-70rc1-x64':
    nodes:
      "debian7.serf.vm":
        prefab: 'debian-70rc1-x64'
  'ubuntu-server-10044-x64':
    nodes:
      "ubuntu10.serf.vm":
        prefab: 'ubuntu-server-10044-x64'
  'ubuntu-server-12042-x64':
    nodes:
      "ubuntu12.serf.vm":
        prefab: 'ubuntu-server-12042-x64'
